In [1]:
# --------------Product Line Profitability & Margin Performance Analysis for Nassau Candy Distributor --------------- #

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('Nassau Candy Distributor (2).csv')

In [4]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [5]:
df.shape

(10194, 18)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [7]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [8]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df[['Sales','Units','Gross Profit']].describe()

              Sales         Units  Gross Profit
count  10194.000000  10194.000000  10194.000000
mean      13.908537      3.791838      9.166451
std       11.341020      2.228317      6.643740
min        1.250000      1.000000      0.250000
25%        7.200000      2.000000      4.900000
50%       10.800000      3.000000      7.470000
75%       18.000000      5.000000     12.250000
max      260.000000     14.000000    130.000000

In [11]:
df[df['Sales'] <= 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost]
Index: []

In [12]:
df[df['Units'] <= 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost]
Index: []

In [13]:
df[df['Cost'] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Country/Region, City, State/Province, Postal Code, Division, Region, Product ID, Product Name, Sales, Units, Gross Profit, Cost]
Index: []

In [14]:
# Gross Margin %
df['Gross Margin %'] = (df['Gross Profit']/df['Sales']) * 100

In [15]:
# Profit Per Unit 
df['Profit per Unit'] = df['Gross Profit'] / df['Units']

In [16]:
# Total profit contribution
total_sales = df['Sales'].sum()
total_profit = df['Gross Profit'].sum()

print('Total Sales', total_sales)
print('Total Profit', total_profit)

Total Sales 141783.63
Total Profit 93442.79999999999

In [17]:
df['Revenue Contribution %'] = (df['Sales'] / total_sales) * 100

In [18]:
df['Profit Contribution %'] = (df['Gross Profit'] / total_profit) * 100

In [19]:
df[['Sales',
    'Units',
    'Gross Profit',
    'Cost',
    'Gross Margin %',
    'Profit per Unit',
    'Revenue Contribution %',
    'Profit Contribution %']].head(10)

,Sales,Units,Gross Profit,Cost,Gross Margin %,Profit per Unit,Revenue Contribution %,Profit Contribution %
0,6.50,2,4.22,2.28,64.923077,2.11,0.004584,0.004516
1,7.50,2,4.90,2.60,65.333333,2.45,0.005290,0.005244
2,10.47,3,7.47,3.00,71.346705,2.49,0.007384,0.007994
3,10.80,3,7.50,3.30,69.444444,2.50,0.007617,0.008026
4,11.25,3,7.35,3.90,65.333333,2.45,0.007935,0.007866
5,32.40,9,22.50,9.90,69.444444,2.50,0.022852,0.024079
6,7.50,2,4.90,2.60,65.333333,2.45,0.005290,0.005244
7,9.75,3,6.33,3.42,64.923077,2.11,0.006877,0.006774
8,6.98,2,4.98,2.00,71.346705,2.49,0.004923,0.005329
9,13.00,4,8.44,4.56,64.923077,2.11,0.009169,0.009032

In [20]:
product_analysis = df.groupby(['Product ID', 'Product Name']).agg({'Sales':'sum',
                                                                   'Units': 'sum',
                                                                   'Gross Profit': 'sum',
                                                                   'Cost':'sum'
                                                                  }).reset_index()

In [21]:
product_analysis.head()

,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,CHO-FUD-51000,Wonka Bar - Fudge Mallows,24890.40,6914,16593.60,8296.80
1,CHO-MIL-31000,Wonka Bar - Milk Chocolate,26867.75,8267,17443.37,9424.38
2,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,23574.95,6755,16819.95,6755.00
3,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,27874.80,7743,19357.50,8517.30
4,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,28485.00,7596,18610.20,9874.80

In [22]:
product_analysis.shape

(15, 6)

In [23]:
product_analysis['Product ID'].nunique()

15

In [24]:
product_analysis.columns

Index(['Product ID', 'Product Name', 'Sales', 'Units', 'Gross Profit', 'Cost'], dtype='object')

In [25]:
product_analysis['Gross Margin %'] = (
    product_analysis['Gross Profit'] /
    product_analysis['Sales']
) * 100

In [26]:
# ----- Top 10 by Sales --------
top_sales = product_analysis.sort_values(
    'Sales',
    ascending=False
).head()
top_sales[['Product Name', 'Sales', 'Gross Profit', 'Gross Margin %']]

                        Product Name     Sales  Gross Profit  Gross Margin %
4  Wonka Bar - Triple Dazzle Caramel  28485.00      18610.20       65.333333
3     Wonka Bar -Scrumdiddlyumptious  27874.80      19357.50       69.444444
1         Wonka Bar - Milk Chocolate  26867.75      17443.37       64.923077
0          Wonka Bar - Fudge Mallows  24890.40      16593.60       66.666667
2  Wonka Bar - Nutty Crunch Surprise  23574.95      16819.95       71.346705

In [27]:
#---- Top 10 by Gross Profit --------
top_profit = product_analysis.sort_values(
    'Gross Profit',
    ascending=False
).head(10)

top_profit[['Product Name', 'Sales', 'Gross Profit', 'Gross Margin %']]

                         Product Name     Sales  Gross Profit  Gross Margin %
3      Wonka Bar -Scrumdiddlyumptious  27874.80      19357.50       69.444444
4   Wonka Bar - Triple Dazzle Caramel  28485.00      18610.20       65.333333
1          Wonka Bar - Milk Chocolate  26867.75      17443.37       64.923077
2   Wonka Bar - Nutty Crunch Surprise  23574.95      16819.95       71.346705
0           Wonka Bar - Fudge Mallows  24890.40      16593.60       66.666667
8                  Lickable Wallpaper   7860.00       3930.00       50.000000
6                           Wonka Gum    597.50        310.70       52.000000
9              Everlasting Gobstopper    130.00        104.00       80.000000
7                           Kazookles   1205.75         92.75        7.692308
11                        Hair Toffee     76.50         59.50       77.777778

In [28]:
# -------- Top 10 by Gross Margin
top_margin = product_analysis.sort_values(
    'Gross Margin %',
    ascending=False
).head(10)

top_margin[['Product Name', 'Sales', 'Gross Profit', 'Gross Margin %']]

                         Product Name     Sales  Gross Profit  Gross Margin %
9              Everlasting Gobstopper    130.00        104.00       80.000000
11                        Hair Toffee     76.50         59.50       77.777778
2   Wonka Bar - Nutty Crunch Surprise  23574.95      16819.95       71.346705
3      Wonka Bar -Scrumdiddlyumptious  27874.80      19357.50       69.444444
0           Wonka Bar - Fudge Mallows  24890.40      16593.60       66.666667
4   Wonka Bar - Triple Dazzle Caramel  28485.00      18610.20       65.333333
1          Wonka Bar - Milk Chocolate  26867.75      17443.37       64.923077
12                        Laffy Taffy     53.73         33.48       62.311558
5                Fizzy Lifting Drinks     78.75         47.25       60.000000
6                           Wonka Gum    597.50        310.70       52.000000

In [29]:
# ------ Bottom 10 by Gross Profit
bottom_profit = product_analysis.sort_values(
    'Gross Profit',
    ascending=True
).head(10)

bottom_profit[['Product Name', 'Sales', 'Gross Profit', 'Gross Margin %']]

              Product Name    Sales  Gross Profit  Gross Margin %
10                 Fun Dip    12.00          4.80       40.000000
13                   Nerds    15.00          7.00       46.666667
14               SweeTARTS    61.50         28.70       46.666667
12             Laffy Taffy    53.73         33.48       62.311558
5     Fizzy Lifting Drinks    78.75         47.25       60.000000
11             Hair Toffee    76.50         59.50       77.777778
7                Kazookles  1205.75         92.75        7.692308
9   Everlasting Gobstopper   130.00        104.00       80.000000
6                Wonka Gum   597.50        310.70       52.000000
8       Lickable Wallpaper  7860.00       3930.00       50.000000

In [30]:
# ----------Bottom 10 by Gross Margin
bottom_margin = product_analysis.sort_values(
    'Gross Margin %',
    ascending=True
).head(10)

bottom_margin[['Product Name', 'Sales', 'Gross Profit', 'Gross Margin %']]

                         Product Name     Sales  Gross Profit  Gross Margin %
7                           Kazookles   1205.75         92.75        7.692308
10                            Fun Dip     12.00          4.80       40.000000
13                              Nerds     15.00          7.00       46.666667
14                          SweeTARTS     61.50         28.70       46.666667
8                  Lickable Wallpaper   7860.00       3930.00       50.000000
6                           Wonka Gum    597.50        310.70       52.000000
5                Fizzy Lifting Drinks     78.75         47.25       60.000000
12                        Laffy Taffy     53.73         33.48       62.311558
1          Wonka Bar - Milk Chocolate  26867.75      17443.37       64.923077
4   Wonka Bar - Triple Dazzle Caramel  28485.00      18610.20       65.333333

In [31]:
sales_median = product_analysis['Sales'].median()
margin_median = product_analysis['Gross Margin %'].median()

print("Sales Median:", sales_median)
print("Margin Median:", margin_median)

Sales Median: 597.5
Margin Median: 62.31155778894474

In [32]:
def classify_product(row):
    if row['Sales'] >= sales_median and row['Gross Margin %'] >= margin_median:
        return 'Star Product'
    elif row['Sales'] < sales_median and row['Gross Margin %'] >= margin_median:
        return 'Growth Opportunity'
    elif row['Sales'] >= sales_median and row['Gross Margin %'] < margin_median:
        return 'Margin Risk'
    else:
        return 'Low Priority'

product_analysis['Profitability Category'] = product_analysis.apply(
    classify_product,
    axis=1
)

In [33]:
product_analysis['Profitability Category'].value_counts()

Profitability Category
Star Product          5
Low Priority          4
Margin Risk           3
Growth Opportunity    3
Name: count, dtype: int64

In [34]:
product_analysis[
    ['Product Name', 'Sales', 'Gross Profit',
     'Gross Margin %', 'Profitability Category']
].sort_values(
    'Profitability Category'
)

,Product Name,Sales,Gross Profit,Gross Margin %,Profitability Category
9,Everlasting Gobstopper,130.00,104.00,80.000000,Growth Opportunity
11,Hair Toffee,76.50,59.50,77.777778,Growth Opportunity
12,Laffy Taffy,53.73,33.48,62.311558,Growth Opportunity
5,Fizzy Lifting Drinks,78.75,47.25,60.000000,Low Priority
10,Fun Dip,12.00,4.80,40.000000,Low Priority
13,Nerds,15.00,7.00,46.666667,Low Priority
14,SweeTARTS,61.50,28.70,46.666667,Low Priority
6,Wonka Gum,597.50,310.70,52.000000,Margin Risk
7,Kazookles,1205.75,92.75,7.692308,Margin Risk
8,Lickable Wallpaper,7860.00,3930.00,50.000000,Margin Risk
0,Wonka Bar - Fudge Mallows,24890.40,16593.60,66.666667,Star Product
1,Wonka Bar - Milk Chocolate,26867.75,17443.37,64.923077,Star Product
2,Wonka Bar - Nutty Crunch Surprise,23574.95,16819.95,71.346705,Star Product
3,Wonka Bar -Scrumdiddlyumptious,27874.80,19357.50,69.444444,Star Product
4,Wonka Bar - Triple Dazzle Caramel,28485.00,18610.20,65.333333,Star Product

In [35]:
division_analysis = df.groupby('Division').agg({
    'Sales':'sum',
    'Units':'sum',
    'Gross Profit':'sum',
    'Cost':'sum'
}).reset_index()

In [36]:
division_analysis['Gross Margin %'] = (division_analysis['Gross Profit'] / division_analysis['Sales'])*100

In [37]:
division_analysis['Revenue Contribution %'] = (
    division_analysis['Sales'] /
    division_analysis['Sales'].sum()
) * 100

In [38]:
division_analysis['Profit Contribution %'] = (
    division_analysis['Gross Profit'] /
    division_analysis['Gross Profit'].sum()
) * 100

In [39]:
division_analysis

,Division,Sales,Units,Gross Profit,Cost,Gross Margin %,Revenue Contribution %,Profit Contribution %
0,Chocolate,131692.90,37275,88824.62,42868.28,67.448298,92.883008,95.057747
1,Other,9663.25,1242,4333.45,5329.80,44.844643,6.815491,4.637543
2,Sugar,427.48,137,284.73,142.75,66.606625,0.301502,0.304710

In [40]:
division_analysis.sort_values('Sales',ascending=False)

,Division,Sales,Units,Gross Profit,Cost,Gross Margin %,Revenue Contribution %,Profit Contribution %
0,Chocolate,131692.90,37275,88824.62,42868.28,67.448298,92.883008,95.057747
1,Other,9663.25,1242,4333.45,5329.80,44.844643,6.815491,4.637543
2,Sugar,427.48,137,284.73,142.75,66.606625,0.301502,0.304710

In [41]:
division_analysis.sort_values(
    'Gross Margin %',
    ascending=False
)

,Division,Sales,Units,Gross Profit,Cost,Gross Margin %,Revenue Contribution %,Profit Contribution %
0,Chocolate,131692.90,37275,88824.62,42868.28,67.448298,92.883008,95.057747
2,Sugar,427.48,137,284.73,142.75,66.606625,0.301502,0.304710
1,Other,9663.25,1242,4333.45,5329.80,44.844643,6.815491,4.637543

In [42]:
product_analysis['Profit Contribution %'] = (
    product_analysis['Gross Profit'] /
    product_analysis['Gross Profit'].sum()
) * 100

In [43]:
profit_pareto = product_analysis.sort_values(
    'Gross Profit',
    ascending=False
).copy()

In [44]:
profit_pareto['Cumulative Profit'] = (
    profit_pareto['Gross Profit'].cumsum()
)

In [45]:
profit_pareto['Cumulative Profit %'] = (
    profit_pareto['Cumulative Profit'] /
    profit_pareto['Gross Profit'].sum()
) * 100

In [46]:
profit_pareto[
    ['Product Name',
     'Gross Profit',
     'Profit Contribution %',
     'Cumulative Profit %']
]

,Product Name,Gross Profit,Profit Contribution %,Cumulative Profit %
3,Wonka Bar -Scrumdiddlyumptious,19357.50,20.715882,20.715882
4,Wonka Bar - Triple Dazzle Caramel,18610.20,19.916141,40.632023
1,Wonka Bar - Milk Chocolate,17443.37,18.667431,59.299454
2,Wonka Bar - Nutty Crunch Surprise,16819.95,18.000263,77.299717
0,Wonka Bar - Fudge Mallows,16593.60,17.758030,95.057747
8,Lickable Wallpaper,3930.00,4.205782,99.263528
6,Wonka Gum,310.70,0.332503,99.596031
9,Everlasting Gobstopper,104.00,0.111298,99.707329
7,Kazookles,92.75,0.099259,99.806588
11,Hair Toffee,59.50,0.063675,99.870263
5,Fizzy Lifting Drinks,47.25,0.050566,99.920829
12,Laffy Taffy,33.48,0.035829,99.956658
14,SweeTARTS,28.70,0.030714,99.987372
13,Nerds,7.00,0.007491,99.994863
10,Fun Dip,4.80,0.005137,100.000000

In [47]:
products_for_80_profit = (
    profit_pareto['Cumulative Profit %'].searchsorted(80) + 1
)

total_products = len(profit_pareto)

percentage_products = (
    products_for_80_profit / total_products
) * 100

print("Products needed for 80% of profit:", products_for_80_profit)
print("Total products:", total_products)
print("Percentage of products:", percentage_products)

Products needed for 80% of profit: 5
Total products: 15
Percentage of products: 33.33333333333333

In [48]:
revenue_pareto = product_analysis.sort_values(
    'Sales',
    ascending=False
).copy()

In [49]:
revenue_pareto['Cumulative Sales'] = (
    revenue_pareto['Sales'].cumsum()
)

In [50]:
revenue_pareto['Cumulative Sales %'] = (
    revenue_pareto['Cumulative Sales'] /
    revenue_pareto['Sales'].sum()
) * 100

In [51]:
revenue_pareto[
    ['Product Name',
     'Sales',
     'Cumulative Sales',
     'Cumulative Sales %']
]

,Product Name,Sales,Cumulative Sales,Cumulative Sales %
4,Wonka Bar - Triple Dazzle Caramel,28485.00,28485.00,20.090472
3,Wonka Bar -Scrumdiddlyumptious,27874.80,56359.80,39.750569
1,Wonka Bar - Milk Chocolate,26867.75,83227.55,58.700394
0,Wonka Bar - Fudge Mallows,24890.40,108117.95,76.255595
2,Wonka Bar - Nutty Crunch Surprise,23574.95,131692.90,92.883008
8,Lickable Wallpaper,7860.00,139552.90,98.426666
7,Kazookles,1205.75,140758.65,99.277082
6,Wonka Gum,597.50,141356.15,99.698498
9,Everlasting Gobstopper,130.00,141486.15,99.790187
5,Fizzy Lifting Drinks,78.75,141564.90,99.845730
11,Hair Toffee,76.50,141641.40,99.899685
14,SweeTARTS,61.50,141702.90,99.943061
12,Laffy Taffy,53.73,141756.63,99.980957
13,Nerds,15.00,141771.63,99.991536
10,Fun Dip,12.00,141783.63,100.000000

In [52]:
products_for_80_revenue = (
    revenue_pareto['Cumulative Sales %'].searchsorted(80) + 1
)

total_products = len(revenue_pareto)

percentage_products_revenue = (
    products_for_80_revenue / total_products
) * 100

print("Products needed for 80% of revenue:", products_for_80_revenue)
print("Total products:", total_products)
print("Percentage of products:", percentage_products_revenue)

Products needed for 80% of revenue: 5
Total products: 15
Percentage of products: 33.33333333333333

In [53]:
profit_pareto[
    ['Product Name', 'Gross Profit', 'Cumulative Profit %']
].head(5)

                        Product Name  Gross Profit  Cumulative Profit %
3     Wonka Bar -Scrumdiddlyumptious      19357.50            20.715882
4  Wonka Bar - Triple Dazzle Caramel      18610.20            40.632023
1         Wonka Bar - Milk Chocolate      17443.37            59.299454
2  Wonka Bar - Nutty Crunch Surprise      16819.95            77.299717
0          Wonka Bar - Fudge Mallows      16593.60            95.057747

In [54]:
revenue_pareto[
    ['Product Name', 'Sales', 'Cumulative Sales %']
].head(5)

                        Product Name     Sales  Cumulative Sales %
4  Wonka Bar - Triple Dazzle Caramel  28485.00           20.090472
3     Wonka Bar -Scrumdiddlyumptious  27874.80           39.750569
1         Wonka Bar - Milk Chocolate  26867.75           58.700394
0          Wonka Bar - Fudge Mallows  24890.40           76.255595
2  Wonka Bar - Nutty Crunch Surprise  23574.95           92.883008

In [55]:
###  The analysis shows a highly concentrated product portfolio. The five core Chocolate products represent only 33.3% of the 15 product portfolio,
#    yet contribute approximately 92.9% of revenue and 95.1% of gross profit. This indicates substantial dependence on a small group of core products.

In [56]:
product_analysis['Cost % of Sales'] = (
    product_analysis['Cost'] /
    product_analysis['Sales']
) * 100

In [57]:
product_analysis[
    ['Product Name',
     'Sales',
     'Cost',
     'Gross Profit',
     'Gross Margin %',
     'Cost % of Sales']
]

,Product Name,Sales,Cost,Gross Profit,Gross Margin %,Cost % of Sales
0,Wonka Bar - Fudge Mallows,24890.40,8296.80,16593.60,66.666667,33.333333
1,Wonka Bar - Milk Chocolate,26867.75,9424.38,17443.37,64.923077,35.076923
2,Wonka Bar - Nutty Crunch Surprise,23574.95,6755.00,16819.95,71.346705,28.653295
3,Wonka Bar -Scrumdiddlyumptious,27874.80,8517.30,19357.50,69.444444,30.555556
4,Wonka Bar - Triple Dazzle Caramel,28485.00,9874.80,18610.20,65.333333,34.666667
5,Fizzy Lifting Drinks,78.75,31.50,47.25,60.000000,40.000000
6,Wonka Gum,597.50,286.80,310.70,52.000000,48.000000
7,Kazookles,1205.75,1113.00,92.75,7.692308,92.307692
8,Lickable Wallpaper,7860.00,3930.00,3930.00,50.000000,50.000000
9,Everlasting Gobstopper,130.00,26.00,104.00,80.000000,20.000000
10,Fun Dip,12.00,7.20,4.80,40.000000,60.000000
11,Hair Toffee,76.50,17.00,59.50,77.777778,22.222222
12,Laffy Taffy,53.73,20.25,33.48,62.311558,37.688442
13,Nerds,15.00,8.00,7.00,46.666667,53.333333
14,SweeTARTS,61.50,32.80,28.70,46.666667,53.333333

In [58]:
cost_heavy = product_analysis.sort_values(
    'Cost % of Sales',
    ascending=False
)

cost_heavy[
    ['Product Name',
     'Sales',
     'Cost',
     'Gross Profit',
     'Gross Margin %',
     'Cost % of Sales']
].head(10)

,Product Name,Sales,Cost,Gross Profit,Gross Margin %,Cost % of Sales
7,Kazookles,1205.75,1113.00,92.75,7.692308,92.307692
10,Fun Dip,12.00,7.20,4.80,40.000000,60.000000
13,Nerds,15.00,8.00,7.00,46.666667,53.333333
14,SweeTARTS,61.50,32.80,28.70,46.666667,53.333333
8,Lickable Wallpaper,7860.00,3930.00,3930.00,50.000000,50.000000
6,Wonka Gum,597.50,286.80,310.70,52.000000,48.000000
5,Fizzy Lifting Drinks,78.75,31.50,47.25,60.000000,40.000000
12,Laffy Taffy,53.73,20.25,33.48,62.311558,37.688442
1,Wonka Bar - Milk Chocolate,26867.75,9424.38,17443.37,64.923077,35.076923
4,Wonka Bar - Triple Dazzle Caramel,28485.00,9874.80,18610.20,65.333333,34.666667

In [59]:
margin_risk = product_analysis[
    product_analysis['Gross Margin %'] < product_analysis['Gross Margin %'].median()
].sort_values('Gross Margin %')

margin_risk[
    ['Product Name',
     'Sales',
     'Cost',
     'Gross Profit',
     'Gross Margin %',
     'Cost % of Sales']
]

,Product Name,Sales,Cost,Gross Profit,Gross Margin %,Cost % of Sales
7,Kazookles,1205.75,1113.0,92.75,7.692308,92.307692
10,Fun Dip,12.00,7.2,4.80,40.000000,60.000000
13,Nerds,15.00,8.0,7.00,46.666667,53.333333
14,SweeTARTS,61.50,32.8,28.70,46.666667,53.333333
8,Lickable Wallpaper,7860.00,3930.0,3930.00,50.000000,50.000000
6,Wonka Gum,597.50,286.8,310.70,52.000000,48.000000
5,Fizzy Lifting Drinks,78.75,31.5,47.25,60.000000,40.000000

In [60]:
sales_median = product_analysis['Sales'].median()
margin_median = product_analysis['Gross Margin %'].median()

def margin_risk_flag(row):
    if row['Gross Margin %'] < margin_median and row['Sales'] >= sales_median:
        return 'High Priority'
    elif row['Gross Margin %'] < margin_median and row['Sales'] < sales_median:
        return 'Monitor'
    else:
        return 'Healthy'

product_analysis['Margin Risk Flag'] = product_analysis.apply(
    margin_risk_flag,
    axis=1
)

In [61]:
product_analysis[
    ['Product Name',
     'Sales',
     'Gross Profit',
     'Gross Margin %',
     'Cost % of Sales',
     'Margin Risk Flag']
].sort_values('Gross Margin %')

,Product Name,Sales,Gross Profit,Gross Margin %,Cost % of Sales,Margin Risk Flag
7,Kazookles,1205.75,92.75,7.692308,92.307692,High Priority
10,Fun Dip,12.00,4.80,40.000000,60.000000,Monitor
13,Nerds,15.00,7.00,46.666667,53.333333,Monitor
14,SweeTARTS,61.50,28.70,46.666667,53.333333,Monitor
8,Lickable Wallpaper,7860.00,3930.00,50.000000,50.000000,High Priority
6,Wonka Gum,597.50,310.70,52.000000,48.000000,High Priority
5,Fizzy Lifting Drinks,78.75,47.25,60.000000,40.000000,Monitor
12,Laffy Taffy,53.73,33.48,62.311558,37.688442,Healthy
1,Wonka Bar - Milk Chocolate,26867.75,17443.37,64.923077,35.076923,Healthy
4,Wonka Bar - Triple Dazzle Caramel,28485.00,18610.20,65.333333,34.666667,Healthy
0,Wonka Bar - Fudge Mallows,24890.40,16593.60,66.666667,33.333333,Healthy
3,Wonka Bar -Scrumdiddlyumptious,27874.80,19357.50,69.444444,30.555556,Healthy
2,Wonka Bar - Nutty Crunch Surprise,23574.95,16819.95,71.346705,28.653295,Healthy
11,Hair Toffee,76.50,59.50,77.777778,22.222222,Healthy
9,Everlasting Gobstopper,130.00,104.00,80.000000,20.000000,Healthy

In [62]:
region_analysis = df.groupby('Region').agg({
    'Sales': 'sum',
    'Units': 'sum',
    'Gross Profit': 'sum',
    'Cost': 'sum'
}).reset_index()

region_analysis['Gross Margin %'] = (
    region_analysis['Gross Profit'] /
    region_analysis['Sales']
) * 100

region_analysis['Revenue Contribution %'] = (
    region_analysis['Sales'] /
    region_analysis['Sales'].sum()
) * 100

region_analysis['Profit Contribution %'] = (
    region_analysis['Gross Profit'] /
    region_analysis['Gross Profit'].sum()
) * 100

region_analysis

,Region,Sales,Units,Gross Profit,Cost,Gross Margin %,Revenue Contribution %,Profit Contribution %
0,Atlantic,41197.24,11159,26973.70,14223.54,65.474532,29.056415,28.866537
1,Gulf,22247.26,6209,14700.67,7546.59,66.078564,15.690993,15.732266
2,Interior,32037.60,8820,21282.49,10755.11,66.429726,22.596121,22.775955
3,Pacific,46301.53,12466,30485.94,15815.59,65.842187,32.656471,32.625242

In [ ]:
df['Order Date'] = pd.to_datetime(
    df['Order Date'],
    format='%d-%m-%Y'
)

In [ ]:
monthly_analysis = df.groupby(
    df['Order Date'].dt.to_period('M')
).agg({
    'Sales': 'sum',
    'Gross Profit': 'sum'
}).reset_index()

monthly_analysis['Order Date'] = monthly_analysis['Order Date'].astype(str)

monthly_analysis

In [ ]:
division_product = df.groupby(
    ['Division', 'Product Name']
).agg({
    'Sales': 'sum',
    'Gross Profit': 'sum',
    'Cost': 'sum',
    'Units': 'sum'
}).reset_index()

division_product['Gross Margin %'] = (
    division_product['Gross Profit'] /
    division_product['Sales']
) * 100

division_product.sort_values(
    ['Division', 'Gross Profit'],
    ascending=[True, False]
)

In [ ]:
df.to_csv('nassau_candy_cleaned.csv', index=False)

In [65]:
df.shape

(10194, 22)